# Generated by Django 4.0.1 on 2022-01-22 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydb',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Email вказано некоректно'}, max_length=30, validators=[django.core.validators.EmailValidator], verbose_name='Email'),
        ),
    ]
